# DOCKER COMPOSE
services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8000:8000"   # Edge / Agent
      - "9443:9443"   # HTTPS (recomendado)
      # - "9000:9000" # HTTP (opcional, evite em produÃ§Ã£o)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  postgres:
    image: postgres:15
    container_name: pg_data
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  airflow-init:
    image: airflow-custom:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-init
    restart: no
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    user: "${AIRFLOW_UID:-50000}:0"
    command: >
      bash -c "airflow db migrate &&
           airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@local --password admin ||
           true"


  airflow-api-server:
    image: airflow-custom:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-api-server
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      redis:
        condition: service_started
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["airflow", "api-server"]
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
#      interval: 30s
#      timeout: 20s
#      retries: 5

  airflow-dag-processor:
    image: airflow-custom:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-dag-processor
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: ["airflow", "dag-processor"]
  airflow-scheduler:
    image: airflow-custom:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      redis:
        condition: service_started
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock      
    command: ["airflow", "scheduler"]


  airflow-worker:
    image: airflow-custom:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-worker
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      redis:
        condition: service_started
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["airflow", "celery", "worker"]


  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    container_name: dbt
    working_dir: /usr/app/dbt
    volumes:
      - ./dbt:/usr/app/dbt
      - ./dbt_profiles:/root/.dbt
    depends_on:
      - postgres
    entrypoint: ["/bin/bash", "-c"]  
    command: tail -f /dev/null


  superset:
    image: apache/superset:latest
    container_name: superset
    restart: unless-stopped
    environment:
      SUPERSET_ENV: production
    volumes:
      - ./superset:/app/superset_home
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
    ports:
      - "8082:8088"
    depends_on:
      - postgres
    command: >
      bash -c "
      superset db upgrade &&
      superset fab create-admin --username admin --password admin --firstname Admin --lastname User --email admin@example.com &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088"

volumes:
  pg_data:
  pgadmin_data:
  portainer_data: